default:
  image: weltn24/up-docker-node-chrome-headless
stages:
  - test
  - e2e

test:
  stage: test
  script: 
    -npm test

e2e:
  stage: e2e
  image: cronn/nodejs-chrome-firefox
  before_script:
    - apt-get -y install openjdk-8-jre
  script:
    -npm run protractor